/*
 * Micro QuickJS compiler
 *
 * Copyright (c) 2017-2025 Fabrice Bellard
 * Copyright (c) 2017-2025 Charlie Gordon
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <inttypes.h>
#include <string.h>
#include <assert.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/wait.h>

#include "cutils.h"
#include "mquickjs.h"
#include "mqjs_runtime.h"

/* we include mqjs_stdlib.h so we have the atoms defined for compilation */
#include "mqjs_stdlib.h"

static void dump_error(JSContext *ctx)
{
    JSValue obj;
    obj = JS_GetException(ctx);
    JS_PrintValueF(ctx, obj, JS_DUMP_LONG);
    printf("\n");
}

static const char main_c_template[] =
    "/* automatically generated by mqjsc */\n"
    "#include <stdlib.h>\n"
    "#include <stdio.h>\n"
    "#include <string.h>\n"
    "#include \"mquickjs.h\"\n"
    "#include \"mqjs_runtime.h\"\n"
    "#include \"mqjs_stdlib.h\"\n"
    "\n"
    "static const uint8_t bytecode[%u] = {";

static const char main_c_template2[] =
    "};\n"
    "\n"
    "int main(int argc, const char **argv)\n"
    "{\n"
    "  uint8_t *mem_buf;\n"
    "  JSContext *ctx;\n"
    "  JSValue val;\n"
    "  size_t mem_size = %u;\n"
    "  mem_buf = malloc(mem_size);\n"
    "  if (!mem_buf) { fprintf(stderr, \"Could not allocate memory\\n\"); return 1; }\n"
    "  ctx = JS_NewContext(mem_buf, mem_size, &js_stdlib);\n"
    "  if (!ctx) { fprintf(stderr, \"Could not create JS context\\n\"); return 1; }\n"
    "\n"
    "  if (argc > 1) {\n"
    "    JSValue obj;\n"
    "    JSGCRef arr_ref;\n"
    "    int i;\n"
    "    JS_AddGCRef(ctx, &arr_ref);\n"
    "    arr_ref.val = JS_NewArray(ctx, argc - 1);\n"
    "    for(i = 1; i < argc; i++) {\n"
    "      JSValue str = JS_NewString(ctx, argv[i]);\n"
    "      JS_SetPropertyUint32(ctx, arr_ref.val, i - 1, str);\n"
    "    }\n"
    "    obj = JS_GetGlobalObject(ctx);\n"
    "    JS_SetPropertyStr(ctx, obj, \"scriptArgs\", arr_ref.val);\n"
    "    JS_DeleteGCRef(ctx, &arr_ref);\n"
    "  }\n"
    "\n"
    "  uint8_t *bytecode_copy = malloc(%u);\n"
    "  if (!bytecode_copy) { fprintf(stderr, \"Could not allocate bytecode copy\\n\"); return 1; }\n"
    "  memcpy(bytecode_copy, bytecode, %u);\n"
    "  if (JS_RelocateBytecode(ctx, bytecode_copy, %u)) {\n"
    "    fprintf(stderr, \"Could not relocate bytecode\\n\");\n"
    "    exit(1);\n"
    "  }\n"
    "  val = JS_LoadBytecode(ctx, bytecode_copy);\n"
    "  val = JS_Run(ctx, val);\n"
    "  if (JS_IsException(val)) {\n"
    "    JSValue obj = JS_GetException(ctx);\n"
    "    JS_PrintValueF(ctx, obj, JS_DUMP_LONG);\n"
    "    fprintf(stderr, \"\\n\");\n"
    "    exit(1);\n"
    "  }\n"
    "  run_timers(ctx);\n"
    "  JS_FreeContext(ctx);\n"
    "  free(bytecode_copy);\n"
    "  free(mem_buf);\n"
    "  return 0;\n"
    "}\n";

static void output_c_code(FILE *f, const uint8_t *bytecode, uint32_t bytecode_len,
                          size_t mem_size)
{
    uint32_t i;

    fprintf(f, main_c_template, bytecode_len);
    for (i = 0; i < bytecode_len; i++) {
        if (i % 16 == 0)
            fprintf(f, "\n  ");
        fprintf(f, "0x%02x,", bytecode[i]);
    }
    fprintf(f, "\n");
    fprintf(f, main_c_template2, (unsigned int)mem_size, bytecode_len, bytecode_len, bytecode_len);
}

static void help(void)
{
    printf("MicroQuickJS compiler\n"
           "usage: mqjsc [options] [file]\n"
           "-h          list options\n"
           "-o FILE     set the output filename\n"
           "-c          only output the C source file\n"
           "-m32        force 32 bit bytecode output\n"
           "--memory-limit n  limit the memory usage to 'n' bytes\n");
    exit(1);
}

int main(int argc, char **argv)
{
    int optind;
    const char *out_filename = "out.exe";
    const char *in_filename;
    BOOL output_c_only = FALSE;
    BOOL force_32bit = FALSE;
    size_t mem_size = 16 << 20;
    uint8_t *mem_buf;
    JSContext *ctx;
    uint8_t *js_buf;
    int js_buf_len;
    JSValue val;
    union {
        JSBytecodeHeader hdr;
#if JSW == 8
        JSBytecodeHeader32 hdr32;
#endif
    } hdr_buf;
    int hdr_len;
    const uint8_t *data_buf;
    uint32_t data_len;
    FILE *f;
    char c_filename[1024];

    optind = 1;
    while (optind < argc && *argv[optind] == '-') {
        const char *arg = argv[optind] + 1;
        const char *longopt = "";
        if (!*arg)
            break;
        optind++;
        if (*arg == '-') {
            longopt = arg + 1;
            arg += strlen(arg);
            if (!*longopt)
                break;
        }
        for (; *arg || *longopt; longopt = "") {
            char opt = *arg;
            if (opt)
                arg++;
            if (opt == 'h' || !strcmp(longopt, "help")) {
                help();
            } else if (opt == 'o') {
                if (*arg) {
                    out_filename = arg;
                    break;
                }
                if (optind < argc) {
                    out_filename = argv[optind++];
                    break;
                }
            } else if (opt == 'c') {
                output_c_only = TRUE;
            } else if (opt == 'm' && !strcmp(arg, "32")) {
                force_32bit = TRUE;
                arg += strlen(arg);
            } else if (!strcmp(longopt, "memory-limit")) {
                if (optind < argc) {
                    char *p;
                    double count = strtod(argv[optind++], &p);
                    switch (tolower((unsigned char)*p)) {
                    case 'g': count *= 1024;
                    case 'm': count *= 1024;
                    case 'k': count *= 1024;
                    default: mem_size = (size_t)count; break;
                    }
                }
            } else {
                fprintf(stderr, "unknown option\n");
                help();
            }
        }
    }

    if (optind >= argc)
        help();

    in_filename = argv[optind];

    mem_buf = malloc(mem_size);
    ctx = JS_NewContext2(mem_buf, mem_size, &js_stdlib, TRUE);

    js_buf = load_file(in_filename, &js_buf_len);
    val = JS_Parse(ctx, (char *)js_buf, js_buf_len, in_filename, 0);
    free(js_buf);

    if (JS_IsException(val)) {
        dump_error(ctx);
        exit(1);
    }

#if JSW == 8
    if (force_32bit) {
        if (JS_PrepareBytecode64to32(ctx, &hdr_buf.hdr32, &data_buf, &data_len, val)) {
            fprintf(stderr, "Could not convert bytecode to 32 bits\n");
            exit(1);
        }
        hdr_len = sizeof(JSBytecodeHeader32);
    } else
#endif
    {
        JS_PrepareBytecode(ctx, &hdr_buf.hdr, &data_buf, &data_len, val);
        JS_RelocateBytecode2(ctx, &hdr_buf.hdr, (uint8_t *)data_buf, data_len, 0, FALSE);
        hdr_len = sizeof(JSBytecodeHeader);
    }

    if (output_c_only) {
        f = fopen(out_filename, "w");
    } else {
        snprintf(c_filename, sizeof(c_filename), "%s.c", out_filename);
        f = fopen(c_filename, "w");
    }
    if (!f) {
        perror("fopen");
        exit(1);
    }

    uint8_t *full_bc = malloc(hdr_len + data_len);
    memcpy(full_bc, &hdr_buf, hdr_len);
    memcpy(full_bc + hdr_len, data_buf, data_len);

    output_c_code(f, full_bc, hdr_len + data_len, mem_size);
    fclose(f);
    free(full_bc);

    if (!output_c_only) {
        pid_t pid;
        int status;
        const char *argv_cc[16];
        int i;

        i = 0;
        argv_cc[i++] = "gcc";
        argv_cc[i++] = "-Os";
        argv_cc[i++] = "-Wall";
        argv_cc[i++] = "-o";
        argv_cc[i++] = out_filename;
        argv_cc[i++] = c_filename;
        argv_cc[i++] = "libmquickjs.a";
        argv_cc[i++] = "-lm";
        if (force_32bit)
            argv_cc[i++] = "-m32";
        argv_cc[i++] = NULL;

        pid = fork();
        if (pid == 0) {
            execvp(argv_cc[0], (char **)argv_cc);
            perror("execvp");
            exit(1);
        } else if (pid < 0) {
            perror("fork");
            exit(1);
        } else {
            waitpid(pid, &status, 0);
            if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
                fprintf(stderr, "C compiler failed\n");
                exit(1);
            }
        }
        unlink(c_filename);
    }

    JS_FreeContext(ctx);
    free(mem_buf);

    return 0;
}
